matrix:
  include:
    - language: python
      dist: xenial
      python:
        - "3.7"
      install:
        - pip install boto3 codecov coverage strict-rfc3339 jsonschema
      # commands to run tests
      before_script:
        - cd ./gtfs/gtfs_utils/gtfs_utils/
        - cp ./config_example.json ./config.json
        - cd -
      script:
        - cd ./gtfs/gtfs_utils
        - python setup.py test
        - cd ../retriever/
        - coverage run s3_wrapper_setup.py pytest
        - cd ../..
        - pwd
        - coverage run -m unittest discover data_stream
        - codecov
    - language: java
      dist: trusty
      jdk: oraclejdk8
      script:
        - cd ./siri/siri_retriever/siri-0.1
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
        - docker build -t siri-collector .
        - export DOCKER_TAG=$(sed 's/\//_/g' <<< ${TRAVIS_BRANCH}) # Replacing slashes in branch name with underscores
        - docker tag siri-collector openbus1/siri-collector:${DOCKER_TAG}
        - docker push openbus1/siri-collector:${DOCKER_TAG}
    - language: java
      dist: trusty
      jdk: oraclejdk8
      script:
        - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
        - cd ./siri/gtfs_reader
        - mvn install
        - docker build -t gtfs-collector .
        - export DOCKER_TAG=$(sed 's/\//_/g' <<< ${TRAVIS_BRANCH}) # Replacing slashes in branch name with underscores
        - docker tag gtfs-collector openbus1/gtfs-collector:${DOCKER_TAG}
        - docker push openbus1/gtfs-collector:${DOCKER_TAG}

